#!/bin/bash

version: '3.8'

services:
  api_admin:
    image: willymaillot87/pompiers_admin-api:latest
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    volumes:
      - ./requirements.txt:/app/requirements.txt
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PWD_DB_WILLY: $PWD_DB_WILLY
      PWD_DB_DJAMEL: $PWD_DB_DJAMEL
      PWD_DB_JONATHAN: $PWD_DB_JONATHAN
      PWD_DB_ROOT: $PWD_DB_ROOT
      PWD_DB_ADMIN: $PWD_DB_ADMIN
      AWS_ADMIN_KEY_ID: $AWS_ADMIN_KEY_ID
      AWS_ADMIN_KEY: $AWS_ADMIN_KEY 
      AWS_USER_KEY_ID: $AWS_USER_KEY_ID 
      AWS_USER_KEY: $AWS_USER_KEY 
      AWS_S3_REGION: $AWS_S3_REGION 
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME 

  api_user:
    image: willymaillot87/pompiers_user-api:latest
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    volumes:
      - ./requirements.txt:/app/requirements.txt
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PWD_DB_WILLY: $PWD_DB_WILLY
      PWD_DB_DJAMEL: $PWD_DB_DJAMEL
      PWD_DB_JONATHAN: $PWD_DB_JONATHAN
      PWD_DB_ROOT: $PWD_DB_ROOT
      PWD_DB_ADMIN: $PWD_DB_ADMIN
      AWS_ADMIN_KEY_ID: $AWS_ADMIN_KEY_ID
      AWS_ADMIN_KEY: $AWS_ADMIN_KEY 
      AWS_USER_KEY_ID: $AWS_USER_KEY_ID 
      AWS_USER_KEY: $AWS_USER_KEY 
      AWS_S3_REGION: $AWS_S3_REGION 
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME 

networks:
  mynetwork: